# Generated by Django 3.0.7 on 2021-05-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0002_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='Location',
        ),
    ]
