# Generated by Django 3.0.7 on 2021-08-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0003_remove_pin_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('pin', 'email')},
        ),
    ]
